### ISSUE TITLE
Feature Request: Capability to Filter Logs by Custom Fields in LogDNA-Agent-v2 Config File

### ISSUE THREAD

**Issue by mos2** [logdna/logdna-agent#102]
We have requirements to be able to send logs from multiple Kubernetes clusters, to one LogDNA instance, and then, filter logs for those clusters by other fields like Kubernetes cluster name, e.g. `clusterName=myCluster`, just like the other line identifier fields in the following screenshot of a Kubernetes pod log:

![Screenshot 2019-06-13 at 12 05 06](https://user-images.githubusercontent.com/1292534/59427844-86299a00-8dd3-11e9-8e48-92c56c41f309.png)

Is anybody else working on a feature to provide this, or is this something planned to be coming relatively soon?

**Comment by CJP10** [comment]
you can use tags
```
 env:
         - name: LOGDNA_TAGS
           value: prod,clustername,etc
```

**Comment by johnymathew** [comment]
@mos2 where are you planning to put the filter? In the logdna instance?

**Comment by snayakie** [comment]
Hi, I'm answering as @mos2 is in my team and is currently OOO.

@johnymathew : We would like to configure it at the logdna agent yaml, so that it can add more metadata regarding the data-source.

@CJP10 yes, we are able to workaround it at present using tags, it would be better to have support for adding `fields` which can be searched by in the search-bar, like `Namespace`, `Container`, etc. Is that planned?

**Comment by peterbytes** [comment]
@snayakie not currently planned, but happy to add it to our backlog for future possible prioritization. I've gone ahead and created a ticket internally and we'll ping you if/when this resurfaces. In the meantime I would recommend following @CJP10's guidance regarding tags. Thank you for bringing this to our attention.
