### ISSUE TITLE
Tags are ignored when payload contains _tag

### ISSUE THREAD

**Issue by nvanheuverzwijn** [logdna/logdna-agent#146]
It seems that logdna agent ignores additionnal tags when the incoming json payload contains a key called `_tag`.
Is this normal ?
It should add the tag in addition to `_tag`.

**Comment by smusali** [comment]
Hi, @nvanheuverzwijn! 

Thanks for bringing this up!

Can you give us example of the payload and/or log line where you are having this issue? Or can you explain more?

Thanks in advance!

Have a good one,
Samir Musali

**Comment by andkon** [comment]
Hey @nvanheuverzwijn; `_tag` is [a reserved field](https://docs.logdna.com/docs/ingestion#section-reserved-fields). To avoid conflicts with the agent's settings and configuration, we're not planning on concatenating or otherwise joining the agent's `_tag` values and those of a JSON log it's trying to send.
