### ISSUE TITLE
Increasing MAX_LINE_LENGTH

### ISSUE THREAD

**Issue by khastings1066** [logdna/logdna-agent#214]
We are seeing some log lines truncated with the message 'cut off, too long...'

How are we able to increase the length of a line allowed?

Thanks!

**Comment by smusali** [comment]
@khastings1066, thanks for your question!

It seems like you are using the older version of the `LogDNA Agent` since we removed `MAX_LINE_LENGTH` configuration variable starting from `v1.6.2` since we do have such protection on our server side and usually that kind of protection / control cannot be overridden.

In order to request an exceptional increase on the line length for your account, you can contact [LogDNA Support](mailto:support@logdna.com).

In any case, we recommend you to upgrade the `LogDNA Agent`.

Have a good one!
